version: "3.7"
services:
  database:
    image: postgres
    container_name: postgres
    restart: always
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: password
      POSTGRES_DB: runner_db #dont change this
    volumes:
      - dbdata:/var/lib/postgresql/data
      - ./init:/docker-entrypoint-initdb.d
  runner:
    container_name: runner
    build:
      context: ./
    restart: always
    ports: 
      - "10000:10000"
    links:
      - database
volumes:
  dbdata:
